---
apiVersion: v1
kind: Service
metadata:
  name: openssh-service
spec:
  type: LoadBalancer
  ports:  
    - protocol: TCP
      port: 2222
      targetPort: 2222
  selector:
    app: spx-app
---
apiVersion: v1
kind: Service
metadata:
  name: spx-service
  annotations: 
    cloud.google.com/neg: '{"exposed_ports": { "80": { "name": "spx-app-neg"} }}'
spec:
  type: LoadBalancer
  ports:
    - protocol: TCP
      port: 80
      targetPort: 5656
  selector:
    app: spx-app