steps:
- name: 'gcr.io/cloud-builders/docker'
  args: ['build', '-t', '${_IMAGE}', '-f', 'kubernetes/Dockerfile', '.']
- name: 'gcr.io/cloud-builders/docker'
  args: ['push', '${_IMAGE}']
substitutions:
  _LOCATION: 'us-central1'
  _IMAGE: '${_LOCATION}-docker.pkg.dev/${PROJECT_ID}/${PROJECT_ID}/spxgc'
  _CLUSTER: 'spx-gc-demo-cluster'
images:
- '${_IMAGE}'